name: mymenu
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.1 #^0.15.5+3
  #here_sdk:
  #  path: plugins/here_sdk
  #here_maps_webservice: 1.0.2
  cloud_firestore: ^0.16.0+1 #0.13.4+2
  # progress_dialog: ^1.2.4 #not used
  provider: ^4.0.4
  flutter_spinkit: "^4.1.2"
  google_maps_flutter: ^0.5.25+3
  # location: 3.2.4 #^2.3.5

  # firebase_messaging: #7.0.3 #6.0.9

  image_picker: ^0.6.0+17
  image_cropper: ^1.2.1

  firebase_storage: ^7.0.0
  fluttertoast: ^7.1.8 #4.0.0

  geoflutterfire: 2.2.2 #2.0.3+2
  geolocator: ^5.3.1
  http: 0.12.2
  latlong2: ^0.8.0

  # flutter_google_places: ^0.2.8 #uses api headers
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1 #5.0.16
  google_sign_in: ^4.5.4
  # flutter_facebook_login: ^3.0.0
  # carousel_slider: ^2.2.1 #not used
  # hexcolor: 2.0.5 #^1.0.6
  # commons: ^0.7.8+3 #uses get version
  cool_alert: ^1.0.3 #replaces commons




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # permission: ^0.1.7
  flutter_polyline_points: ^0.2.2
  flutter_inappwebview: ^4.0.0+4
  # webview_flutter: ^1.0.7 #not used yet
  # flutter_webview_plugin: ^0.4.0 #0.3.11
  sleek_circular_slider: ^1.2.0+web
  # flutter_linkify: ^3.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  # dependency_validator: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - Picture/car_icon.png
  - Picture/avatar.png
  - Picture/delDocLogo.png
  - Picture/HalaLogo.jpeg
  - Picture/HalaTransparent.jpeg
  - Picture/HalaWhite.png
  - Picture/preparingOrder.gif
  - Picture/halaimbiza.jpeg
  - Picture/halaDarkComplexionPots.jpg
  - Picture/halaNopotyi.jpeg
  - Picture/HalaNovelty.jpg
  - Picture/IHalaPots.jpg
  - Picture/hala_sign_in.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
